// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgbzaoyauazabbmfqixf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnYnphb3lhdWF6YWJibWZxaXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDk3NDgsImV4cCI6MjA2MzU4NTc0OH0.Xf1c0K2rCQMc3_aVFRIQjPJsN0ABm2AumL21EBcYKM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);